### ISSUE TITLE
ニュースのリンク切れ直しました

### ISSUE THREAD

**Issue by ShigeruIchinoki** [KahokuHanten/oyako#92]
news[" link"]をnews["link"]に（linkの前の半角スペースとる）

**Comment by sasai** [comment]
#91 の Issue にコメントを追加するという形でお願いします。
（状態に合わせてタイトルを変更するわけではないです）

**Comment by sasai** [comment]
#91 を Reopen しておきましたので、#91 に追記お願いします。
